### ISSUE TITLE
[Request] Enable the syntax "NL" in GUI buttons

### ISSUE THREAD

**Issue by Webbstre** [GarageGames/Torque2D#215]
I'm discovering that making larger buttons where one word appears below another word in GUI buttons is extremely difficult. The biggest suggestion I've gotten is to make new GuiTextCtrl children of the button, but honestly getting it to resize properly is extremely difficult, and you have to add a lot more code simply to get a line break.

The other Torque Syntax options ( @ , TAB, and SPC ) all appear to work when processed in this manner, but the NL only displays a square where the line break should be. I'm hoping this request isn't too hard (Especially since in my web search I discovered it was typically much easier to do a line break in competing engines).

**Comment by chaigler** [comment]
@capnlove is correct. GuiMLTextCtrl is intended to be used for mult-line text. If you need multi-line text in your buttons, simply create a new GuiMLTextCtrl and parent it to the button control. 

The reason other syntax options (such as TAB and SPC) work with GuiTextCtrl is because the control's "text" field gets processed by the console system, which manually inserts spaces accordingly. 

You could rewrite GuiTextCtrl to support newline commands but there's really no need. I recommend closing this issue.

**Comment by greenfire27** [comment]
Recommendation accepted.
