### ISSUE TITLE
Fill Battle Tutorial issue

### ISSUE THREAD

**Issue by alesliehughes** [GarageGames/Torque2D#245]
In the T2D 3.0 there is
ButtonBehavior::onTouchUp
...
while (%stackObject.len > 0)

However the T2D 2.0

function ButtonBehavior::onTouchUp
....
while (%locStack.len > 0)

....
Should the version 3.0 being using %locStack instread?

Using the 3.0 code, every time I click on a colour it goes into any infinity loop?

Also what is the purpose of %counter in the 3.0 version?

**Comment by lilligreen** [comment]
Hello,
 
Sorry for the confusion – since 3.0 has been out for so long now, this tutorial should have been updated to get rid of the 2.0 code. The difference has to do with ScriptObjects.
 
In the 2.0 code, the actual ScriptObject is assigned to the local variable %locStack.
 
In the 3.0 code, the ScriptObject is assigned to the local variable %stackObject. The %locStack variable gets used for a behavior instance attached to %stackObject. In the stack behavior that is created in step 3, the len field is assigned to the owner of this behavior, and not the behavior itself. So the len field ends up on %stackObject.
 
The 2.0 code is in some ways a bit simpler since it doesn’t deal with behaviors – the stack methods (and the len field) are assigned to the ScriptObject %locStack via a class.
 
The endless loops are probably due to an error or typo somewhere in your code. I’ll see if I can find some time to update the tutorial are remove the confusing dual versions in chapter 6, which might help make tracking down the issue a bit easier.
 
As for %counter, it looks like that is some debug code that I forgot to remove when publishing the tutorial. It has no purpose as shown.

**Comment by greenfire27** [comment]
The Fill battle tutorial is becoming increasingly outdated and remains only partially complete. We will likely remove it in the months to come to make room for updated tutorials.  In the meantime it appears that this issue is due to a typo.  I'm closing the issue.
