### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by kynora** [GarageGames/Torque2D#316]
error message :
"vorbis/vorbisfile.h" file not found.

**Comment by greenfire27** [comment]
iOS doesn't support ogg as far as I know.  We'll need to use a compiler directive to fix this.  Also, it might be worth putting out a hotfix since we had a similar problem with Android and we want the master branch to work.

We will try to get this working again for you within a few days Kynora.  Thanks for posting the error.

**Comment by chaigler** [comment]
Found this, can someone more familiar with iOS & xcode take a look:
https://code.google.com/p/play-ogg-vorbis-ios/

**Comment by greenfire27** [comment]
As a short-term fix I've corrected this in development by disabling the ogg code on iOS.  Someday we'll add support in.  The good news is that it should compile again so I'm closing this issue.
