### ISSUE TITLE
ImageFont

### ISSUE THREAD

**Issue by yurembo** [GarageGames/Torque2D#329]
Hi!
I read docs about my favourite object ImageFont and looked that it will be replaced in the next engine version.
Currently I use Torque 3.2 and don't test new dev branch.
Will you delete ImageFont from the engine?
And should I upgrade my games to suppot TextSprite?
Or ImageFont suppot should stay?

**Comment by greenfire27** [comment]
Yes, ImageFont will be gone with the next update and will be replaced with the TextSprite.  The main difference is that the TextSprite takes a FontAsset.  Also you can set the size of the TextSprite and then the text will appear inside the box of the TextSprite (with word wrapping if you want).  There's also a host of new features that are demonstrated in the new TextSprite Toy.  I've written the documentation for the FontAsset and will be writing documentation soon for the TextSprite too.  We will not be keeping the ImageFont class because it is highly out gunned by the TextSprite.
