### ISSUE TITLE
Torque script comparing string and integer

### ISSUE THREAD

**Issue by kynora** [GarageGames/Torque2D#348]
```
%savedPlayerSide = "Red";
if (%savedPlayerSide == 0)
      %savedPlayerSide = "";
```

echo %savedPlayerSide is empty string not "Red", is comparing operator bug?

**Comment by greenfire27** [comment]
I haven't run across this before, but my guess is that the engine tries to convert the string "Red" to a number before doing the **number comparison**.  Since "Red" is not a number it converts it to 0 and the condition is true.  Try using the **string comparison** operator instead:

`if (%savedPlayerSide $= "0")`

I bet that will work for you.

**Comment by capnlove** [comment]
Yes $= should definitely do the trick from my experience

**Comment by kynora** [comment]
Yes, it work for me. I have no any request, so I close this bug.
